quarkus:
  http:
    host: 0.0.0.0
    port: 8180

  datasource:
    db-kind: postgresql
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    reactive:
      url: "postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      max-size: 20
    jdbc:
      enable: true
      url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

  rest-client:
    logging:
      scope: request-response
      body-limit: 50
    coinmarketcap:
      url: https://pro-api.coinmarketcap.com

  log:
    category:
      "io.quarkus.rest.client.reactive.runtime.JacksonResponseMimeTypeSetter":
        level: TRACE
      "org.jboss.resteasy.reactive.client":
        level: DEBUG

"%test":
  CMC_API_KEY: "test-api-key-dummy-value"
  quarkus:
    datasource:
      db-kind: postgresql
      devservices:
        enabled: true
        image-name: postgres:15-alpine
    rest-client:
      coinmarketcap:
        url: http://localhost:8089
