quarkus:
  http:
    host: 0.0.0.0
    port: 8180

  datasource:
    db-kind: postgresql

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

  rest-client:
    coinmarketcap:
      url: https://pro-api.coinmarketcap.com

"%dev":
  quarkus:
    datasource:
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      jdbc:
        enabled: true
        url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      reactive:
        url: "postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
        max-size: 20

"%prod":
  quarkus:
    datasource:
      username: "${DB_USERNAME}"
      password: "${DB_PASSWORD}"
      jdbc:
        enabled: true
        url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      reactive:
        url: "postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
        max-size: 20

"%test":
  CMC_API_KEY: "test-api-key-dummy-value"
  quarkus:
    datasource:
      devservices:
        enabled: true
        image-name: postgres:15-alpine

    rest-client:
      coinmarketcap:
        url: http://localhost:8089