CREATE TABLE product (
     id BIGSERIAL PRIMARY KEY,
     sku VARCHAR(8) NOT NULL UNIQUE,
     name VARCHAR(100) NOT NULL,
     price NUMERIC(10,2) NOT NULL,
     stock INTEGER NOT NULL,
     active BOOLEAN NOT NULL
);